// Code generated by "stringer -type=Suit,Rank"; DO NOT EDIT.

package deck

import "strconv"

const _Suit_name = "SpadeDiamondsClubsHearts"

var _Suit_index = [...]uint8{0, 5, 13, 18, 24}

func (i Suit) String() string {
	if i < 0 || i >= Suit(len(_Suit_index)-1) {
		return "Suit(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Suit_name[_Suit_index[i]:_Suit_index[i+1]]
}

const _Rank_name = "ATwoThreeFourFiveSixSevenEightNineTenJQK"

var _Rank_index = [...]uint8{0, 1, 4, 9, 13, 17, 20, 25, 30, 34, 37, 38, 39, 40}

func (i Rank) String() string {
	i -= 1
	if i < 0 || i >= Rank(len(_Rank_index)-1) {
		return "Rank(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Rank_name[_Rank_index[i]:_Rank_index[i+1]]
}
